apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: realtor_project
  annotations:
    github.com/project-slug: Anirudh-Brillio/realtor_project
spec:
  type: other
  lifecycle: unknown
  owner: "Guests"  # Example value, replace with appropriate owner information
